// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', // zeigt intro.md an
      label: 'Projektüberblick',
    },
    {
      type: 'category',
      label: 'Entwicklung',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'development', // generiert aus docs/development/
        },
      ],
    },
  ],
};

export default sidebars;
